services:
  backend:
    build: ./backend
    image: streko/projektowanie-obiektowe:zadanie09.backend-3.0
    container_name: zadanie09-backend
    ports:
      - "8080:8080"
    networks:
      - cloud

  frontend:
    build: ./frontend
    image: streko/projektowanie-obiektowe:zadanie09.frontend-3.0
    container_name: zadanie09-frontend
    environment:
      - API_URL=http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - cloud

networks:
  cloud:
    driver: bridge
